name: Testing Atlas Build

on:
    push:
        branches: [master]
        paths:
            - "packages/theming/atlas/**"
            - "!**/*.md"
    pull_request:
        branches: [master]
        paths:
            - "packages/theming/atlas/**"
            - "!**/*.md"

jobs:
    test:
        name: "Testing Atlas Build"
        runs-on: ubuntu-latest

        steps:
            - name: "Checking-out code"
              uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3
            - name: "Defining node version"
              uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # v3
              with:
                  node-version-file: ".nvmrc"
                  cache: "npm"
                  cache-dependency-path: "**/package-lock.json"
            - name: "Installing dependencies"
              run: npm run bootstrap
            - name: "Running Atlas build"
              run: |
                  cd packages/theming/atlas
                  npm run build -- --validate-sass
