name: Testing Atlas Build

on:
    push:
        branches: [master]
        paths:
            - "packages/theming/atlas/**"
            - "!**/*.md"
    pull_request:
        branches: [master]
        paths:
          - "packages/theming/atlas/**"
          - "!**/*.md"

jobs:
    test:
        name: "Testing Atlas Build"
        runs-on: ubuntu-latest

        steps:
            - name: "Checking-out code"
              uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2
              with:
                  submodules: false
            - name: "Defining node version"
              uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # v3
              with:
                  node-version-file: '.nvmrc'
                  cache: 'npm'
                  cache-dependency-path: '**/package-lock.json'
            - name: "Installing dependencies"
              run: npm run bootstrap
            - name: "Running Atlas build"
              run: |
                  cd packages/theming/atlas
                  npm run build -- --validate-sass
