name: Run build

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    lint:
        name: "Lint"
        runs-on: ubuntu-latest

        steps:
            - name: "Checking-out code"
              uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3
              with:
                  fetch-depth: 0
            - name: "Defining node version"
              uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # v3
              with:
                  node-version-file: ".nvmrc"
                  cache: "npm"
                  cache-dependency-path: "**/package-lock.json"
            - name: "Installing dependencies"
              run: npm run bootstrap
            - name: "Linting code (MR)"
              if: github.event_name == 'pull_request'
              run: npm run lint -- --since origin/${{ github.base_ref }}
            - name: "Linting code"
              if: github.event_name != 'pull_request'
              run: npm run lint
    build:
        name: "Build (${{ matrix.os }})"
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]

        steps:
            - name: "Checking-out code"
              uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3
              with:
                  fetch-depth: 0
            - name: "Defining node version"
              uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # v3
              with:
                  node-version-file: ".nvmrc"
                  cache: "npm"
                  cache-dependency-path: "**/package-lock.json"
            - name: "Installing dependencies"
              run: npm run bootstrap
            - name: "Running build for development (MR)"
              if: github.event_name == 'pull_request'
              run: npm run build -- --since origin/${{ github.base_ref }}
              env:
                  NODE_OPTIONS: --max_old_space_size=8192
            - name: "Running build for development"
              if: github.event_name != 'pull_request'
              run: npm run build
              env:
                  NODE_OPTIONS: --max_old_space_size=8192
    test:
        name: "Unit tests"
        runs-on: ubuntu-latest

        steps:
            - name: "Checking-out code"
              uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3
              with:
                  fetch-depth: 0
            - name: "Defining node version"
              uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # v3
              with:
                  node-version-file: ".nvmrc"
                  cache: "npm"
                  cache-dependency-path: "**/package-lock.json"
            - name: "Installing dependencies"
              run: npm run bootstrap
            - name: "Running unit tests (MR)"
              if: github.event_name == 'pull_request'
              run: npm run test -- --since origin/${{ github.base_ref }}
            - name: "Running unit tests"
              if: github.event_name != 'pull_request'
              run: npm run test
