name: Create web release

on:
    workflow_dispatch:
        inputs:
            widget-name:
                description: "Web Widget/Module to release"
                required: true

jobs:
    release:
        name: "Create web widget/module release"
        runs-on: ubuntu-latest

        steps:
            - name: "Checking-out code"
              uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3
            - name: "Defining node version"
              uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # v3
              with:
                  node-version-file: ".nvmrc"
                  cache: "npm"
                  cache-dependency-path: "**/package-lock.json"
            - name: "Installing dependencies"
              run: npm run bootstrap
            - name: "Building ${{ github.event.inputs.widget-name }}"
              run: "npm run release -- --scope '${{ github.event.inputs.widget-name }}'"
            - name: "Creating ${{ github.event.inputs.widget-name }} widget release"
              if: ${{ endsWith(github.event.inputs.widget-name, '-web') }}
              run: "npm run release-github:widget '${{ github.event.inputs.widget-name }}'"
              env:
                  GH_USERNAME: ${{ secrets.GH_USERNAME }}
                  GH_EMAIL: ${{ secrets.GH_EMAIL }}
                  GH_NAME: ${{ secrets.GH_NAME }}
                  GH_PAT: ${{ secrets.GH_PAT }}
            - name: "Creating ${{ github.event.inputs.widget-name }} module release"
              if: ${{ !endsWith(github.event.inputs.widget-name, '-web') }}
              run: "npm run create-modules:web '${{ github.event.inputs.widget-name }}'"
              env:
                  GH_USERNAME: ${{ secrets.GH_USERNAME }}
                  GH_EMAIL: ${{ secrets.GH_EMAIL }}
                  GH_NAME: ${{ secrets.GH_NAME }}
                  GH_PAT: ${{ secrets.GH_PAT }}
