name: Run release

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    test:
        name: "Release (${{ matrix.os }})"
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]

        steps:
            - name: "Checking changed files"
              id: files
              uses: softprops/diffset@3aeca0719d5043522e155012d3c9f7470fdd2dc6 # v1
              if:
                  github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name ==
                  github.repository
              with:
                  global_files: |
                      !{packages/**/*,configs/e2e/*.json,scripts/**/*,data/**/*}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: "Checking-out code"
              uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3
              with:
                  fetch-depth: 0
            - name: "Defining environment variables"
              if: startsWith(matrix.os, 'ubuntu')
              id: variablesLinux
              run:
                  echo "::set-output name=arg::$(if [ "${{ steps.files.outputs.global_files }}" = "" ] && ${{
                  github.event_name == 'pull_request' }}; then echo '--since origin/${{ github.base_ref }}'; else echo
                  ''; fi)"
            - name: "Defining environment variables"
              if: startsWith(matrix.os, 'windows')
              id: variablesWindows
              run:
                  echo "::set-output name=arg::$(If ('${{ steps.files.outputs.global_files }}' -eq '' -AND '${{
                  github.event_name == 'pull_request' }}' -eq 'true'){ echo '--since origin/${{ github.base_ref }}' }
                  Else { echo '' })"
            - name: "Defining node version"
              uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # v3
              with:
                  node-version-file: ".nvmrc"
                  cache: "npm"
                  cache-dependency-path: "**/package-lock.json"
            - name: "Installing dependencies"
              run: npm run bootstrap
            - name: "Running release for production"
              run: npm run release -- ${{ steps.variablesLinux.outputs.arg }} ${{ steps.variablesWindows.outputs.arg }}
              env:
                  NODE_OPTIONS: --max_old_space_size=8192
