name: Ensure SHA pinned actions

on:
    push:
        branches: [master]
        paths:
            - ".github/workflows/*.yml"
    pull_request:
        branches: [master]
        paths:
            - ".github/workflows/*.yml"

jobs:
    harden_security:
        name: Check SHA in GH Actions
        runs-on: ubuntu-latest
        steps:
            - name: "Checking-out code"
              uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3
            - name: "Ensure SHA pinned actions"
              uses: zgosalvez/github-actions-ensure-sha-pinned-actions@0b552a197e44b819629237e065d781f5ca691460 # v1.1.1
